services:
  aavail-forecast-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./reports:/app/reports
